from .spnet import *
from .customcnn import *
from .classifier_rgb import *
from .classifier1 import *
from .classifier_rgbd import *
from .classifier_kpts import *
from .classifier_kpts_5class import *
from .classifier_kpts_depth import *
from .classifier_raw_rgb import *
from .classifier_kpts3d import *
from .classifier_kpts3d_5class import *
